"""
Django settings for RGG project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#RGG Project Host
PROJECT_HOST = "ajserensits"

#RGG Specific URLs
USER_CONFIG_URL = "RGG/rgg_configuration/user_credentials.json"
SESSIONS_CONFIG_URL = "RGG/rgg_configuration/sessions.json"
NUMBER_MAPPING_URL = "RGG/rgg_configuration/number_mapping.json"
WORKFLOW_CONFIG_URL = "RGG/rgg_configuration/workflows.json"
HOURS_OF_OPERATION_URL = "RGG/rgg_configuration/hours_of_operation.json"


#RGG Call Flow URLs
RECORDINGS_URL = "https://" + PROJECT_HOST + ".pythonanywhere.com/media/recordings/"
GATHER_URL = "https://" + PROJECT_HOST + ".pythonanywhere.com/gather/"
DYK_URL = "https://" + PROJECT_HOST + ".pythonanywhere.com/dyk/"


#RGG Call Logs
START_LOG_URL = "RGG/call_logs/start_log.txt"
CLOSED_LOG_URL = "RGG/call_logs/closed_log.txt"
SHORT_LOG_URL = "RGG/call_logs/short_log.txt"
MAIN_LOG_URL = "RGG/call_logs/main_log.txt"
FORWARD_LOG_URL = "RGG/call_logs/forward_log.txt"
DYK_LOG_URL = "RGG/call_logs/dyk_log.txt"

#RGG Media URLs
SPREADSHEETS_URL = "RGG/media/spreadsheets/"
MP3_URLS = "RGG/media/recordings/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u4c$tbw7p7a-67o-8%!c-bxgyyhxcm)mrakn5j*nffci+vy=9q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [u'ajserensits.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RGG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RGG.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = u'/home/ajserensits/RGG/media'
MEDIA_URL = '/media/'
STATIC_ROOT = u'/home/ajserensits/RGG/static'
STATIC_URL = '/static/'


